services:
  client_service_db:
    image: postgres:15
    container_name: client_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client_service
    ports:
      - "5432:5432"
    volumes:
      - client_service_data:/var/lib/postgresql/data

  payment_service_db:
    image: postgres:15
    container_name: payment_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service
    ports:
      - "5433:5432"
    volumes:
      - payment_service_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka
      - kafka_tools:/opt/kafka/bin  # Добавляем volume для инструментов

  client_service:
    build:
      context: ./client-service  # Убедитесь, что здесь путь к вашей папке с клиентским сервисом
    container_name: client_service
    depends_on:
      - client_service_db
      - kafka
    environment:
      DB_HOST: client_service_db
      DB_PORT: 5432
      DB_NAME: client_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8000:8000"
    command: ["./wait-for-kafka.sh"]

  payment_service:
    build:
      context: ./payment-service  # Убедитесь, что здесь путь к вашей папке с платежным сервисом
    container_name: payment_service
    depends_on:
      - payment_service_db
      - kafka
    environment:
      DB_HOST: payment_service_db
      DB_PORT: 5432
      DB_NAME: payment_service
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8001:8000"
    command: ["./wait-for-kafka.sh"]

volumes:
  client_service_data:
  payment_service_data:
  kafka_data:
  kafka_tools:  # Добавляем volume для Kafka инструментов
